verbose = true
no_progress = true
base = "https://coderrvse.github.io/fc-barcelona-kids/"
accept = [200,204,206,301,302,307,308,429]
max_concurrency = 4
timeout = 20
max_retries = 2
retry_wait_time = 2
exclude_mail = true
exclude = [
  "https://fonts.googleapis.com",
  "https://fonts.gstatic.com",
  "https://twitter.com", "https://x.com",
  "https://facebook.com", "https://www.facebook.com",
  "https://instagram.com", "https://www.instagram.com",
  "https://youtube.com", "https://www.youtube.com",
  "mailto:*", "tel:*", "data:*"
]