name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"  # daily 07:00 UTC

jobs:
  lhci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Run Lighthouse CI
        run: |
          npx --yes @lhci/cli@0.13.x autorun \
            --collect.url="https://coderrvrse.github.io/fc-barcelona-kids/" \
            --collect.numberOfRuns=3 \
            --collect.headful=false

      - name: Upload Lighthouse results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-results
          path: .lighthouseci/
          retention-days: 7