name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee (JSON report)
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .lychee.toml --format json --output lychee.json .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload lychee report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee.json
          retention-days: 7