name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lychee:
    # Skip on Dependabot and skip PRs from forks (avoid flaky externals)
    if: |
      github.actor != 'dependabot[bot]' &&
      (github.event_name != 'pull_request' ||
       github.event.pull_request.head.repo.full_name == github.repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee (JSON report)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config .lychee.toml --format json --output lychee.json .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload lychee report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee.json
          retention-days: 7