name: Link Check

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - "**/*.html"
      - "**/*.md"
      - ".lychee.toml"
      - ".github/workflows/links.yml"

jobs:
  lychee:
    if: |
      github.actor != 'dependabot[bot]' &&
      (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false)
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4

      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --accept 200,204,301,302,303,307,308,429
            --max-concurrency 4
            --timeout 20s
            --format json
            --output lychee.json
            --config .lychee.toml
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee.json
          retention-days: 7