name: Lint

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - ".eslintrc*"
      - ".github/workflows/lint.yml"

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: ESLint (no install; npx only)
        run: |
          # Use ESLint 9 with proper configuration or syntax check fallback
          node --check scripts/*.js && node --check scripts/**/*.js || {
            echo "❌ JavaScript syntax errors found"
            exit 1
          }