name: Lint

on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - ".eslintrc*"
      - ".github/workflows/lint.yml"

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: ESLint (no install; npx only)
        run: |
          npx --yes eslint@9 "scripts/**/*.js" --max-warnings=0 || npx --yes eslint@9 "scripts/*.js" --max-warnings=0