name: Visual Regression

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"   # daily at 08:00 UTC

concurrency:
  group: visual-regression
  cancel-in-progress: true

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    # Use the official Playwright image with browsers preinstalled.
    container:
      image: mcr.microsoft.com/playwright:v1.48.2-jammy
      options: --ipc=host

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # If we add a package.json later, this becomes deterministic and fast.
      # For now, it will no-op (no package-lock).
      - name: Install deps (with retries)
        run: |
          set -e
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-timeout 600000
          npm ci || npm install

      # Ensure folders exist so artifact steps never warn
      - name: Ensure artifact dirs
        run: mkdir -p test-results playwright-report

      # Run Playwright tests. Force stable conditions for screenshots.
      - name: Run visual tests
        env:
          # Force reduced motion (avoids animation diffs)
          PLAYWRIGHT_PREFER_REDUCED_MOTION: "1"
          # Force deterministic timezone/locale if tests care
          TZ: "UTC"
        run: |
          npx playwright test --reporter=line

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/**
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/**
          if-no-files-found: ignore
          retention-days: 7