name: Visual Regression

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"  # daily 08:00 UTC

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npx --yes playwright@1 install --with-deps chromium webkit

      - name: Run Visual Tests
        run: |
          npx --yes playwright@1 test

      - name: Upload Visual Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7